# Generated by Django 5.1.7 on 2025-06-25 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('main_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle principal')),
                ('secondary_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle secundaria')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de casa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto Fijo')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('used', models.BooleanField(default=False)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], max_length=50, null=True)),
                ('estado_pago', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notifications/files/')),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('coupon', 'Cupón de Descuento'), ('catalog', 'Catálogo de Productos')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Pedido Aprobado'), ('dispatching', 'En Despacho'), ('shipped', 'Pedido Enviado'), ('delivered', 'Pedido Entregado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('delivery_code', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=8, null=True)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('confirm_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('confirmado_por_token', models.BooleanField(default=False)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_envio', models.CharField(choices=[('standard', 'Estándar'), ('express', 'Exprés')], default='standard', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('numero_orden', models.CharField(blank=True, max_length=13, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_verificacion', models.CharField(choices=[('verificar', 'Verificar'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='verificar', max_length=10)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('ultimo_inicio_sesion', models.DateTimeField(auto_now=True)),
                ('suscripcion_boletin', models.BooleanField(default=False)),
                ('cuenta_verificada', models.BooleanField(default=False)),
                ('puntos_fidelidad', models.PositiveIntegerField(default=0)),
                ('codigo_referido', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('coins', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
