# Generated by Django 5.2.5 on 2026-01-28 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_address_apartment_address_floor_address_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(blank=True, help_text='ID de la preferencia de pago', max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, help_text='ID único del cobro en MP', max_length=100, null=True, unique=True)),
                ('status', models.CharField(default='pending', help_text='Estado: approved, pending, rejected, etc.', max_length=50)),
                ('status_detail', models.CharField(blank=True, help_text='Detalle: accredited, insufficient_amount, etc.', max_length=100, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de MP para auditoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_mp', to='perfil.order')),
            ],
        ),
    ]
