# Generated by Django 5.2.5 on 2026-01-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_transaccionmercadopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('qr', 'Código QR'), ('qr_modal', 'Código QR (Modal)'), ('mercadopago', 'Mercado Pago (Link)'), ('mp_redirect', 'Mercado Pago (Checkout Pro)')], max_length=50),
        ),
    ]
