# Generated by Django 5.2.5 on 2025-09-23 01:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('producto_id', models.UUIDField()),
                ('titulo_producto', models.CharField(max_length=255)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prioridad', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('no_atendida', 'No atendida')], default='pendiente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('max_consultas', models.IntegerField(default=5)),
                ('ultima_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaginaVisitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('marca_tiempo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('tipo_reclamo', models.CharField(choices=[('no_llego', 'No me llegó el envío'), ('producto_roto', 'Producto roto'), ('producto_incorrecto', 'Producto incorrecto'), ('falta_producto', 'Faltó un producto en mi pedido'), ('demora_envio', 'Demora en el envío'), ('defectuoso', 'Producto defectuoso'), ('mala_atencion', 'Mala atención al cliente'), ('error_cobro', 'Error en el cobro'), ('cancelacion', 'Quiero cancelar mi pedido'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('prioridad', models.IntegerField(default=1)),
                ('referencia_pedido', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento_asignado', models.CharField(blank=True, choices=[('logistica', 'Logística'), ('soporte', 'Soporte Técnico'), ('facturacion', 'Facturación'), ('atencion_cliente', 'Atención al Cliente')], max_length=50, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=1)),
                ('has_results', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('marca_tiempo', models.DateTimeField(auto_now_add=True)),
                ('marca_tiempo_fin', models.DateTimeField(blank=True, null=True)),
                ('agente_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('navegador', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('dispositivo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('conteo_visitas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
