# Generated by Django 5.2.5 on 2025-09-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
