# Generated by Django 5.2.5 on 2025-09-28 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_total_visitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLoginLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_issued', models.GenericIPAddressField(blank=True, null=True)),
                ('ua_issued', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='user_magicl_email_2e4154_idx'), models.Index(fields=['expires_at'], name='user_magicl_expires_1470f0_idx')],
            },
        ),
    ]
