# Generated by Django 5.2.5 on 2025-09-29 02:12

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_magicloginlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpeg', null=True, upload_to=apps.user.models.user_avatar_upload_path),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MGR', 'Manager'), ('EMP', 'Empleado'), ('CUS', 'Cliente')], db_index=True, default='CUS', max_length=10),
        ),
    ]
