# Generated by Django 5.2.5 on 2026-01-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCompartir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_vistas', models.PositiveIntegerField(default=30, help_text='Cantidad de vistas únicas necesarias para ganar el premio.', verbose_name='Meta de Vistas')),
                ('premio_coins', models.DecimalField(decimal_places=2, default=500.0, help_text='Cantidad de Coins a otorgar al cumplir la meta.', max_digits=10, verbose_name='Premio en Coins')),
            ],
            options={
                'verbose_name': 'Configuración de Referidos',
                'verbose_name_plural': 'Configuración de Referidos',
            },
        ),
        migrations.AddField(
            model_name='productshare',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
