# Generated by Django 5.2.5 on 2026-01-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Asis', max_length=50)),
                ('personality', models.TextField(default='Eres un vendedor profesional, amable y divertido de la tienda NextGen. Tu objetivo es ayudar a comprar y resolver dudas sobre la tienda.')),
                ('restrictions', models.TextField(default='SOLO respondes sobre productos de la tienda, envíos, contacto y ofertas. Si te preguntan sobre programación, código, política o temas ajenos, responde amablemente que solo eres un asistente de compras y no puedes hablar de eso.')),
            ],
        ),
        migrations.CreateModel(
            name='BotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Ej: Horarios, Contacto, Devoluciones', max_length=100)),
                ('content', models.TextField(help_text='La respuesta que el bot debe saber sobre este tema.')),
            ],
        ),
        migrations.CreateModel(
            name='BotOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_text', models.TextField(help_text="Texto de venta: Ej: '¡Este monitor está al 20% off solo por hoy!'")),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_promotions', to='shops.product')),
            ],
        ),
    ]
